project_identifier: liftago-mktp
api_key: d7518e59c3054336b131605cf48169e5
base_path: ./src/translations

files:
  -
    source: '/DriverReg.pot'
    translation: '/%two_letters_code%.po'
    ignore:
      - /cs
      - /pl
      - /sk
